#!/bin/bash
dir_path =`pwd`

sudo apt-get install python-virtualenv
pip install virtualenv
virtualenv -p python2 venv-tcc
source venv-tcc/bin/activate
pip install "django<2.0"
pip install flask
pip install opencv-python
pip install matplotlib
pip install scikit-fuzzy
sudo apt-get install python-tk
pip install redis
pip install matplotlib
pip install requests
